services:
  postgres:
    image: postgres:16

    container_name: strapi-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi123

    ports:
      - "5432:5432"

    volumes:
      - ./postgres:/var/lib/postgresql/data
