name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to VPS
        run: |
          cd /root/muro-backend

          echo "Pull latest code"
          git pull origin main

          echo "Install dependencies"
          npm install

          echo "Build application"
          npm run build || true

          echo "Restart PM2"
          pm2 restart muro-backend

          echo "Save PM2"
          pm2 save
